const flightData = [
  {
    id: 1,
    airline: "Air India",
    from: "Delhi",
    to: "Mumbai",
    departureTime: "08:00",
    arrivalTime: "10:30",
    price: 5000,
  },
  {
    id: 2,
    airline: "IndiGo",
    from: "Delhi",
    to: "Mumbai",
    departureTime: "10:30",
    arrivalTime: "13:00",
    price: 5500,
  },
  {
    id: 3,
    airline: "SpiceJet",
    from: "Delhi",
    to: "Mumbai",
    departureTime: "12:00",
    arrivalTime: "14:30",
    price: 4800,
  },
  {
    id: 4,
    airline: "Air India",
    from: "Mumbai",
    to: "Delhi",
    departureTime: "09:00",
    arrivalTime: "11:30",
    price: 5200,
  },
  {
    id: 5,
    airline: "IndiGo",
    from: "Mumbai",
    to: "Delhi",
    departureTime: "11:30",
    arrivalTime: "14:00",
    price: 5700,
  },
  {
    id: 6,
    airline: "SpiceJet",
    from: "Mumbai",
    to: "Delhi",
    departureTime: "13:00",
    arrivalTime: "15:30",
    price: 4900,
  },
  {
    id: 7,
    airline: "Air India",
    from: "Delhi",
    to: "Bangalore",
    departureTime: "07:00",
    arrivalTime: "10:00",
    price: 6000,
  },
  {
    id: 8,
    airline: "IndiGo",
    from: "Delhi",
    to: "Bangalore",
    departureTime: "09:30",
    arrivalTime: "12:30",
    price: 6500,
  },
  {
    id: 9,
    airline: "SpiceJet",
    from: "Delhi",
    to: "Bangalore",
    departureTime: "12:00",
    arrivalTime: "15:00",
    price: 5800,
  },
  {
    id: 10,
    airline: "Air India",
    from: "Bangalore",
    to: "Delhi",
    departureTime: "08:00",
    arrivalTime: "11:00",
    price: 6200,
  },
  {
    id: 11,
    airline: "IndiGo",
    from: "Bangalore",
    to: "Delhi",
    departureTime: "10:30",
    arrivalTime: "13:30",
    price: 6700,
  },
  {
    id: 12,
    airline: "SpiceJet",
    from: "Bangalore",
    to: "Delhi",
    departureTime: "13:00",
    arrivalTime: "16:00",
    price: 5900,
  },
  {
    id: 13,
    airline: "Air India",
    from: "Mumbai",
    to: "Bangalore",
    departureTime: "08:30",
    arrivalTime: "10:30",
    price: 5500,
  },
  {
    id: 14,
    airline: "IndiGo",
    from: "Mumbai",
    to: "Bangalore",
    departureTime: "11:00",
    arrivalTime: "13:00",
    price: 6000,
  },
  {
    id: 15,
    airline: "SpiceJet",
    from: "Mumbai",
    to: "Bangalore",
    departureTime: "13:30",
    arrivalTime: "15:30",
    price: 5300,
  },
  {
    id: 16,
    airline: "Air India",
    from: "Bangalore",
    to: "Mumbai",
    departureTime: "08:00",
    arrivalTime: "10:00",
    price: 5600,
  },
  {
    id: 17,
    airline: "IndiGo",
    from: "Bangalore",
    to: "Mumbai",
    departureTime: "10:30",
    arrivalTime: "12:30",
    price: 6100,
  },
  {
    id: 18,
    airline: "SpiceJet",
    from: "Bangalore",
    to: "Mumbai",
    departureTime: "13:00",
    arrivalTime: "15:00",
    price: 5400,
  },
  {
    id: 19,
    airline: "Air India",
    from: "Delhi",
    to: "Mumbai",
    departureTime: "08:00",
    arrivalTime: "10:00",
    price: 4000,
  },
  {
    id: 20,
    airline: "IndiGo",
    from: "Mumbai",
    to: "Delhi",
    departureTime: "11:00",
    arrivalTime: "13:00",
    price: 4500,
  },
];
